controllers:
    resource:
        path: ../src/UserInterface/Controller/
        namespace: App\UserInterface\Controller
    type: attribute
    
# index:
#     path: /
#     controller: App\UserInterface\Controller\HomeController
